setECSSourcePrefixV4(32)
setECSSourcePrefixV6(128)
controlSocket('127.0.0.1:5199')
setConsoleACL('0.0.0.0/0')
setKey("YjNUOVRYOXl6OGFKWDRYWGhuQWhYQXlQVzM3UVA0WHk=")
setAPIWritable(false)
setLocal("127.0.0.1:53", {reusePort=true})

setACL({'0.0.0.0/0','::/0' })
setServerPolicy(roundrobin)
newServer({
  address="127.0.0.1:5133",
  name="powerdns",
  pool="powerdnspool",
  sockets=1,
  useClientSubnet=true
})

pc = newPacketCache(4000000, {keepStaleData=True, maxTTL=60, minTTL=0, temporaryFailureTTL=5, staleTTL=60, dontAge=True})
getPool("powerdnspool"):setCache(pc)

webserver("127.0.0.1:5180")
setWebserverConfig({
  password="YjNUOVRYOXl6OGFKWDRYWGhuQWhYQXlQVzM3UVA0WHk=",
  apiKey="YjNUOVRYOXl6OGFKWDRYWGhuQWhYQXlQVzM3UVA0WHk=",
  statsRequireAuthentication=false,
  acl="0.0.0.0/0"
})
