---
services:
  console:
    image: banoleb666/dnsconsole-manager:0.0.2
    # build: .
    container_name: dist-manager
    network_mode: host
    # ports:
    #   - "5000:5000"
    volumes:
      # Persist database (with some test data)
      - ./app/dnsdist_webapi.db:/app/dnsdist_webapi.db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: console
