[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:agent]
command=python3 webapi-agent.py
directory=/app
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/agent.log
stderr_logfile=/var/log/supervisor/agent.error.log
